#!/bin/sh

PICO8_BIN=/Applications/PICO-8.app/Contents/MacOS/pico8

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PICO8_HOME="${SCRIPT_DIR}/pico8-home"
$PICO8_BIN -home "${PICO8_HOME}"  -root_path  "${PICO8_HOME}/carts"
